### PR TITLE
Made stabby/index.js more secure

### PR DESCRIPTION
**Pull request by Starnamics**
Shortened file by using textContent to just set body text instead of setting entire HTML.

Also prevented against XSS by using textContent

### CODE REVIEW

**Comment by User9684** [comment]
you defeated the whole purpose of the link by removing the embed tags

**Comment by Starnamics** [comment]
when testing, i could do <script>alert("hello")</script>

**Comment by User9684** [comment]
ok but you still defeated the entire purpose of the stabby file by removing the embed

**Comment by Starnamics** [comment]
im confused

**Comment by Starnamics** [comment]
it doesnt remove the embed??

**Comment by User9684** [comment]
yes it does?????

**Comment by User9684** [comment]
the embed is created by the .js and your thing removes it

**Comment by User9684** [comment]
removed*

**Comment by Starnamics** [comment]
add the embed to the .html file then?

**Comment by Starnamics** [comment]
it wouldnt show either way cause js isnt ran when showing embed (for discord and twitter and stuf)

**Comment by User9684** [comment]
yea ik which is why its better off to just delete this entirely

**Comment by Starnamics** [comment]
okay

**Pull request closed without merging**
